# Code to reproduce the figures found by Myles in Excel
Read in CO2 emissions per year, define a series of constants (not sure where these come from at the moment) and reproduce the graphs that Myles made in excel. The calculation of non-CO2 ERF changes prior to 2000, adding some complication to the code.
Next steps are to add error bars.

In [239]:
import numpy as np
import pandas as pd

In [240]:
### define constants to be used. These are found in cells ' Time Series' BB6-BB9 in Myles spreadsheet, 

alpha = 0   
AGWP100 = 91.7   
H = 100  
TCRE = 0.00045  

### More constants
contrail_ERF = 0.000000000936 ### contrail ERF, see Master ERF Table C7
nonco2_erf_yr2000 = 35.00 ### 'Time Series' AZ30
co2_emm_yr2000 = 685.5 ### 'Time Series' AX30
contrail_erf_yr2000 = 28.35 ### 'time series' AO30
initial_non_co2_erf = 14.15072653 ### 'time series' AZ10
initial_date = 1980

In [241]:
### read in the data (I'm not sure how to do this all from GITHUB, so code currently reads it in from my computer's harddrive)

co2_forcing = pd.read_csv(r'C:\Users\galla\Documents\University Physics\Fourth Year Notes\MPhys_Project\2020_12_01InitialPaper\FlyingClimate-main\FlyingClimate-main\data\CO2.csv')

co2_emm = pd.read_csv(r'C:\Users\galla\Documents\University Physics\Fourth Year Notes\MPhys_Project\2020_12_01InitialPaper\CO2_emm_data.csv')
co2_forcing = co2_forcing[1:].astype(float)
#co2_forcing
#co2_emm

In [242]:
### remove null lines

co2 = co2_emm.dropna(subset=['Tg/yr'])
#co2

### Pre 2000s
We will generate columns with the following headings for the dates pre 2000

'CO2 emm', 'non CO2 ERF', 'Cum CO2', 'Cum CO2 -fe', 'CO2 Warming', 'Non-CO2 warming'

In [243]:
### take only pre 2000 years of co2 data
co2_pre2000 = co2.iloc[:20].reset_index(drop=True)

In [244]:
### non co2 ERf
# first find contrail erf
contrail_erf = co2_pre2000['Contrail Distance/ km'] * contrail_ERF
## next add contrail erf and other non co2 erf's
non_co2_erf = contrail_erf + ((nonco2_erf_yr2000 - contrail_erf_yr2000) * co2_pre2000['Tg/yr'] / co2_emm_yr2000)
#non_co2_erf_df = pd.DataFrame(non_co2_erf, columns=['non CO2 ERF'])
co2_pre2000['non CO2 ERF'] = non_co2_erf
#co2_pre2000

In [245]:
### Cumulative CO2

cum_co2 = []
for i in range(1, len(co2_pre2000) + 1) :
    co2_sum = co2_pre2000.iloc[:i, 1]
    cum_co2_i = co2_sum.sum(axis=0)/1000
    cum_co2.append(cum_co2_i)

        
co2_pre2000['Cum CO2'] = cum_co2
#co2_pre2000

In [246]:
# Cumulative CO2-fe  - not sure what this is
cum_fe = (1 - alpha) * (H / AGWP100) * (co2_pre2000['non CO2 ERF'] - initial_non_co2_erf) + (alpha/AGWP100) * \
            initial_non_co2_erf * (co2_pre2000['Date'] - initial_date)
co2_pre2000['Cum CO2-fe'] = cum_fe
#co2_pre2000

In [247]:
### CO2 Warming
co2_pre2000['CO2 Warming'] = co2_pre2000['Cum CO2'] * TCRE
#co2_pre2000

In [248]:
### non CO2 Warming
co2_pre2000['non-CO2 Warming'] = co2_pre2000['Cum CO2-fe'] * TCRE
co2_pre2000

,Date,Tg/yr,Contrail Distance/ km,median total non co2 erf,non CO2 ERF,Cum CO2,Cum CO2-fe,CO2 Warming,non-CO2 Warming
0,1980,406.8,1.090000e+10,NaN,14.148746,0.4068,-0.002160,0.000183,-9.720378e-07
1,1981,399.9,1.060000e+10,NaN,13.801009,0.8067,-0.381371,0.000363,-1.716170e-04
2,1982,405.1,1.070000e+10,NaN,13.945054,1.2118,-0.224288,0.000545,-1.009298e-04
3,1983,411.9,1.100000e+10,NaN,14.291821,1.6237,0.153865,0.000731,6.923917e-05
4,1984,439.4,1.180000e+10,NaN,15.307397,2.0631,1.261363,0.000928,5.676135e-04
5,1985,453.3,1.240000e+10,NaN,16.003840,2.5164,2.020843,0.001132,9.093795e-04
6,1986,478.7,1.340000e+10,NaN,17.186244,2.9951,3.310270,0.001348,1.489621e-03
7,1987,500.7,1.430000e+10,NaN,18.242065,3.4958,4.461656,0.001573,2.007745e-03
8,1988,525.0,1.520000e+10,NaN,19.320198,4.0208,5.637373,0.001809,2.536818e-03
9,1989,546.7,1.570000e+10,NaN,19.998708,4.5675,6.377298,0.002055,2.869784e-03
10,1990,549.6,1.680000e+10,NaN,21.056441,5.1171,7.530768,0.002303,3.388846e-03
11,1991,531.5,1.660000e+10,NaN,20.693654,5.6486,7.135144,0.002542,3.210815e-03
12,1992,532.8,1.830000e+10,NaN,22.297465,6.1814,8.884121,0.002782,3.997854e-03
13,1993,535.7,2.000000e+10,NaN,23.916798,6.7171,10.650023,0.003023,4.792511e-03
14,1994,561.2,2.130000e+10,NaN,25.380972,7.2783,12.246724,0.003275,5.511026e-03
15,1995,574.9,2.270000e+10,NaN,26.824275,7.8532,13.820664,0.003534,6.219299e-03
16,1996,600.9,2.400000e+10,NaN,28.293300,8.4541,15.422653,0.003804,6.940194e-03
17,1997,619.2,2.520000e+10,NaN,29.594027,9.0733,16.841113,0.004083,7.578501e-03
18,1998,631.4,2.620000e+10,NaN,30.648379,9.7047,17.990897,0.004367,8.095903e-03
19,1999,651.8,2.770000e+10,NaN,32.250278,10.3565,19.737788,0.004660,8.882005e-03

# Post 2000

In [249]:
### post 2000 co2 data

co2_post2000 = co2.iloc[20:].reset_index(drop=True)
#co2_post2000

In [250]:
### non co2_erf
co2_forcing['mean'] = (co2_forcing['LinClim.1'] + co2_forcing['CICERO.1'] + co2_forcing['FAIR.1']) / 3
AF = co2_forcing['mean'][60:].reset_index(drop=True).astype(float)
AU = co2_post2000['median total non co2 erf'].reset_index(drop=True).astype(float)
co2_post2000['non CO2 ERF'] = AU - AF
#co2_post2000

In [259]:
### cumulative co2
cum_co2_all = np.cumsum(co2['Tg/yr'])/1000
cum_co2_post = cum_co2_all[20:]
co2_post2000['Cum CO2'] = cum_co2_post.reset_index(drop=True)
#cum_co2_post.reset_index(drop=True)

In [260]:
### cum non co2
cum_fe_post = (1 - alpha) * (H / AGWP100) * (co2_post2000['non CO2 ERF'] - initial_non_co2_erf) + (alpha/AGWP100) * \
            initial_non_co2_erf * (co2_post2000['Date'] - initial_date)
co2_post2000['Cum CO2-fe'] = cum_fe_post
#co2_post2000

In [261]:
### co2 warming
co2_post2000['CO2 Warming'] = co2_post2000['Cum CO2'] * TCRE
#co2_post2000

In [265]:
# non co2 warming

co2_post2000['non-CO2 Warming'] = co2_post2000['Cum CO2-fe'] * TCRE
#co2_post2000

In [266]:
co2_pre2000.append(co2_post2000).reset_index(drop=True)

,Date,Tg/yr,Contrail Distance/ km,median total non co2 erf,non CO2 ERF,Cum CO2,Cum CO2-fe,CO2 Warming,non-CO2 Warming
0,1980,406.8,1.090000e+10,NaN,14.148746,0.4068,-0.002160,0.000183,-9.720378e-07
1,1981,399.9,1.060000e+10,NaN,13.801009,0.8067,-0.381371,0.000363,-1.716170e-04
2,1982,405.1,1.070000e+10,NaN,13.945054,1.2118,-0.224288,0.000545,-1.009298e-04
3,1983,411.9,1.100000e+10,NaN,14.291821,1.6237,0.153865,0.000731,6.923917e-05
4,1984,439.4,1.180000e+10,NaN,15.307397,2.0631,1.261363,0.000928,5.676135e-04
5,1985,453.3,1.240000e+10,NaN,16.003840,2.5164,2.020843,0.001132,9.093795e-04
6,1986,478.7,1.340000e+10,NaN,17.186244,2.9951,3.310270,0.001348,1.489621e-03
7,1987,500.7,1.430000e+10,NaN,18.242065,3.4958,4.461656,0.001573,2.007745e-03
8,1988,525.0,1.520000e+10,NaN,19.320198,4.0208,5.637373,0.001809,2.536818e-03
9,1989,546.7,1.570000e+10,NaN,19.998708,4.5675,6.377298,0.002055,2.869784e-03
10,1990,549.6,1.680000e+10,NaN,21.056441,5.1171,7.530768,0.002303,3.388846e-03
11,1991,531.5,1.660000e+10,NaN,20.693654,5.6486,7.135144,0.002542,3.210815e-03
12,1992,532.8,1.830000e+10,NaN,22.297465,6.1814,8.884121,0.002782,3.997854e-03
13,1993,535.7,2.000000e+10,NaN,23.916798,6.7171,10.650023,0.003023,4.792511e-03
14,1994,561.2,2.130000e+10,NaN,25.380972,7.2783,12.246724,0.003275,5.511026e-03
15,1995,574.9,2.270000e+10,NaN,26.824275,7.8532,13.820664,0.003534,6.219299e-03
16,1996,600.9,2.400000e+10,NaN,28.293300,8.4541,15.422653,0.003804,6.940194e-03
17,1997,619.2,2.520000e+10,NaN,29.594027,9.0733,16.841113,0.004083,7.578501e-03
18,1998,631.4,2.620000e+10,NaN,30.648379,9.7047,17.990897,0.004367,8.095903e-03
19,1999,651.8,2.770000e+10,NaN,32.250278,10.3565,19.737788,0.004660,8.882005e-03
20,2000,685.5,3.030000e+10,56.78,35.006667,11.0420,22.743664,0.004969,1.023465e-02
21,2001,659.4,3.050000e+10,57.31,34.903333,11.7014,22.630978,0.005266,1.018394e-02
22,2002,660.7,2.970000e+10,57.23,34.210000,12.3621,21.874889,0.005563,9.843700e-03
23,2003,660.3,3.100000e+10,58.90,35.296667,13.0224,23.059913,0.005860,1.037696e-02
24,2004,701.9,3.510000e+10,63.82,39.550000,13.7243,27.698226,0.006176,1.246420e-02
25,2005,736.4,3.710000e+10,66.70,41.726667,14.4607,30.071909,0.006507,1.353236e-02
26,2006,744.9,3.870000e+10,68.95,43.286667,15.2056,31.773108,0.006843,1.429790e-02
27,2007,766.6,4.070000e+10,71.80,45.413333,15.9722,34.092265,0.007187,1.534152e-02
28,2008,763.0,4.170000e+10,73.45,46.380000,16.7352,35.146427,0.007531,1.581589e-02
29,2009,723.6,4.060000e+10,72.71,45.023333,17.4588,33.666965,0.007856,1.515013e-02
30,2010,760.1,4.470000e+10,77.61,49.276667,18.2189,38.305278,0.008199,1.723738e-02
31,2011,782.7,4.710000e+10,80.38,51.366667,19.0016,40.584449,0.008551,1.826300e-02
32,2012,791.1,4.830000e+10,82.07,52.383333,19.7927,41.693137,0.008907,1.876191e-02
33,2013,813.6,4.980000e+10,84.28,53.923333,20.6063,43.372527,0.009273,1.951764e-02
34,2014,839.2,5.180000e+10,87.05,55.970000,21.4455,45.604442,0.009650,2.052200e-02
35,2015,885.1,5.440000e+10,90.55,58.696667,22.3306,48.577906,0.010049,2.186006e-02
36,2016,927.9,5.740000e+10,94.52,61.900000,23.2585,52.071182,0.010466,2.343203e-02
37,2017,982.6,6.010000e+10,98.44,64.980000,24.2411,55.429960,0.010908,2.494348e-02
38,2018,1033.7,6.130000e+10,100.95,66.620000,25.2748,57.218401,0.011374,2.574828e-02